### ISSUE TITLE
Crash report on server (Terrablender and biolith issue, I think)

### ISSUE THREAD

**Issue by chrispzg** [TerraformersMC/Biolith#18]
[crash-2024-11-19_03.55.33-server.txt](https://github.com/user-attachments/files/17810935/crash-2024-11-19_03.55.33-server.txt)

I'm using sinytra connector by the way, I dont think that was the problem since it has worked very well for loading both mods, terrablender-fabric and biolith-fabric

**Comment by gniftygnome** [comment]
There is no version of Biolith for Forge on 1.20.1.  This is not a supported configuration, and crashes are expected.
