### ISSUE TITLE
Supposed issue with biolith?

### ISSUE THREAD

**Issue by MysticcX** [TerraformersMC/Biolith#6]
A little context:

So I have a modpack of mine and I had a world gen mod (Regions Unexplored) installed and I usually use William Whythers Overhauled Overworld generation so once that updated to 1.20 I added it to see if it was compatible with Regions. Turned out its not so I removed WWOO and it made my world unplayable despite nothing from WWOO being generated. It sucked but I wanted Whythers over Regions so I swapped them along with updating Better Nether/End.

I tried creating a new world and once I try to actually generate it, it automatically loads to the Saving World page and it crashes and from what I can tell it says its a Biolith issue trying to place nether biomes. So I switched back to my old BCLib and Better Nether/End and tried again and it still comes up with same crash report. (At this point I had all the same mods in my pack without Regions) Tried one more time with Regions and same crash report:

https://pastebin.com/ZKFjwtiu (Link to report so this page isn't cluttered)

Not sure what happened as I have the same modset but my client will refuse to generate a world now. Regions Unexplored or William Whythers installed or not the crash report says something about Biolith and I don't have it installed directly.

**Comment by gniftygnome** [comment]
Upgrade Traverse to the latest version (currently 7.0.8 -- https://modrinth.com/mod/traverse/version/7.0.8 )

**Comment by gniftygnome** [comment]
Resolved in current mod versions.
